<a href="https://colab.research.google.com/github/seopseop77/ML/blob/main/iris_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. 모듈 및 데이터 불러오기


In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
import pandas as pd 
from sklearn.datasets import load_iris 
iris_dataset = load_iris()

print("iris_datasetd의 키 : \n",iris_dataset.keys())

iris_datasetd의 키 : 
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


2. 데이터 출력

In [2]:
# data의 처음 다섯 행 
print(iris_dataset['data'][:5])

# data의 처음 다섯 행 (다른 방식) 
import seaborn as sns 
iris_dataset2 = sns.load_dataset('iris')
iris_dataset2.head()

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
print(iris_dataset['target_names'])
print(iris_dataset['feature_names'])

print(iris_dataset['target'])
print(type(iris_dataset['target'])) 
print(iris_dataset['target'].shape)

['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
<class 'numpy.ndarray'>
(150,)


3. 데이터 분리


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'],iris_dataset['target'],random_state = 0)

In [7]:
print(X_train.shape)
print(X_test.shape)
print(type(X_train.shape))
print(type(X_test.shape))

(112, 4)
(38, 4)
<class 'tuple'>
<class 'tuple'>


In [8]:
print(y_train.shape)
print(y_test.shape)
print(type(y_train.shape))
print(type(y_test.shape))

(112,)
(38,)
<class 'tuple'>
<class 'tuple'>


4. 코랩에서 드라이브 마운트

In [10]:
from google.colab import drive 
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


5.모델 생성

In [17]:
from sklearn.neighbors import KNeighborsClassifier 
knn = KNeighborsClassifier(n_neighbors=1)

In [18]:
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

6.새 데이터에 대해 예측

In [20]:
X_new = np.array([[5,2.9,1,0.2]])
print(X_new.shape)

prediction = knn.predict(X_new)
print("prediction result",prediction)
print("target name of perdiction result",iris_dataset['target_names'][prediction])


(1, 4)
prediction result [0]
target name of perdiction result ['setosa']
