<a href="https://colab.research.google.com/github/seopseop77/ML/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np

In [4]:
def removemark(s): # 문자열에서 문장부호 제거 
    marklist = ['.',',','?','!',':',';']
    word = s
    for mark in marklist:
        word = word.replace(mark,'') 
    return word 

In [5]:
def getBoW(s): # 문자열의 단어가 출현한 횟수를 value값으로 하는 딕셔너리 반환 
    text_list = s.split()
    bow_dic = {}
    marklist = ['.',',','?','!',':',';']
    
    for i in text_list:
        word = removemark(i)

        if word in bow_dic.keys():
            bow_dic[word] += 1 
        else:
            bow_dic[word] = 1 
    
    return bow_dic
print(getBoW('John also likes to watch football games. I like to watch football, too.'))

{'John': 1, 'also': 1, 'likes': 1, 'to': 2, 'watch': 2, 'football': 2, 'games': 1, 'I': 1, 'like': 1, 'too': 1}


In [7]:
def n_gram(sentence,n): # 문장을 n 개 단어씩 묶어 출력 
    
    text_list = sentence.split()
    wordlist = []
    for i in range(len(text_list)-n+1):
        st = ''
        
        for j in range(i,i+n):
            st += removemark(text_list[j]) + ' ' 
        st = st.rstrip() 
        wordlist.append(st) 
    return wordlist 

print(n_gram("워너브라더스에서는 DCEU(DC  확장 유니버스)와 상관없는 조커 영화가 하나 더 제작된다.",4))

['워너브라더스에서는 DCEU(DC 확장 유니버스)와', 'DCEU(DC 확장 유니버스)와 상관없는', '확장 유니버스)와 상관없는 조커', '유니버스)와 상관없는 조커 영화가', '상관없는 조커 영화가 하나', '조커 영화가 하나 더', '영화가 하나 더 제작된다']


In [111]:
# 텍스트를 벡터로 변환 및 onehot 인코딩 

from sklearn.preprocessing import Binarizer
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?',
 ]

freq   = CountVectorizer()
corpus_freq = freq.fit_transform(corpus)
print(corpus_freq.toarray())
print('-------------------------')

onehot = Binarizer()
corpus_onehot = onehot.fit_transform(corpus_freq.toarray())
print(corpus_onehot)
print('-------------------------')

X = freq.transform(['and is this this two ten'])
print(X.toarray())
new_onehot = onehot.fit_transform(X.toarray())
print(new_onehot)
print('-------------------------')




[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]
-------------------------
[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]
-------------------------
[[1 0 0 1 0 0 0 0 2]]
[[1 0 0 1 0 0 0 0 1]]
-------------------------


In [110]:
def makeonehot(corpus): # 문장 리스트를 원핫 인코딩으로 변경하는 함수 
  freq   = CountVectorizer()
  corpus_freq = freq.fit_transform(corpus)

  onehot = Binarizer()
  corpus_onehot = onehot.fit_transform(corpus_freq.toarray())
  
  return corpus_onehot

print(makeonehot(corpus))

[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [25]:
# jaccard index를 이용한 유사도 측정 및 챗봇 개발 

def jaccard(str1, str2): 
    a = set(str1.lower().split()) 
    b = set(str2.lower().split())
    x,y = [],[]
    for word in a: 
      x.append(removemark(word))
    for word in b: 
      y.append(removemark(word))
    a = set(x)
    b = set(y)

    c = a.intersection(b)
   
    return float(len(c)) / (len(a) + len(b) - len(c))

conversations = {
    "hello": "Hello!",
    "hi": "Hi!",
    "how are you": "I'm doing well, thank you.",
    "bye": "Goodbye!",
   "what's your name": "My name is Chatbot!",
    "how old are you": "I am a computer program, so I don't age.",
    "what's the time": "I am not sure, can you please tell me the time?",
    "what's your favorite color": "I am a machine, I do not have the ability to perceive or appreciate color",
    "what's your favorite food": "I am a machine, I do not have the ability to eat or have preferences for food",
    "what's the weather like today": "I am not sure, can you please tell me the current weather?",
    "what's the capital of France": "The capital of France is Paris",
    "what's the capital of Germany": "The capital of Germany is Berlin",
    "what's the capital of Korea": "The capital of Korea is Seoul",
    "what's the capital of India": "The capital of India is New Delhi",
   "what's the population of France": "The population of France is approximately 67 million people",
    "what's the population of Germany": "The population of Germany is approximately 83 million people",
    "what's the population of Korea": "The population of China is approximately 50 million people",
    "what's the population of India": "The population of India is approximately 1.4 billion people",
   "What do you do": "I am a chatbot, my main function is to respond to your queries and converse with you."
}

def chat(message):
    
    if message in conversations.keys():
        return conversations[message]
    else:
      max = 0 
      maxsentence = ''
      
      for sentence in conversations.keys():
        if jaccard(sentence,message) > max :
          max = jaccard(sentence,message)
          maxsentence = sentence 
      
      if max > 0.3:
        return conversations[maxsentence]

      else:

        return "I'm sorry, I don't understand what you're saying."

print(chat("hello"))
print(chat("hi"))
print(chat("how are you"))
print(chat("what is your name"))



Hello!
Hi!
I'm doing well, thank you.
My name is Chatbot!


In [38]:
# Cosine similarity를 이용하여 유사도 측정 및 챗봇 개발 

def cal_cossimilarity(sen1,sen2):
  array = makeonehot([sen1,sen2])
  return np.dot(array[0],array[1])/(sum(array[0])*sum(array[1]))

#print(cal_cossimilarity('hello bye','hello hi'))

conversations = {
    "hello": "Hello!",
    "hi": "Hi!",
    "how are you": "I'm doing well, thank you.",
    "bye": "Goodbye!",
   "what's your name": "My name is Chatbot!",
    "how old are you": "I am a computer program, so I don't age.",
    "what's the time": "I am not sure, can you please tell me the time?",
    "what's your favorite color": "I am a machine, I do not have the ability to perceive or appreciate color",
    "what's your favorite food": "I am a machine, I do not have the ability to eat or have preferences for food",
    "what's the weather like today": "I am not sure, can you please tell me the current weather?",
    "what's the capital of France": "The capital of France is Paris",
    "what's the capital of Germany": "The capital of Germany is Berlin",
    "what's the capital of Korea": "The capital of Korea is Seoul",
    "what's the capital of India": "The capital of India is New Delhi",
   "what's the population of France": "The population of France is approximately 67 million people",
    "what's the population of Germany": "The population of Germany is approximately 83 million people",
    "what's the population of Korea": "The population of China is approximately 50 million people",
    "what's the population of India": "The population of India is approximately 1.4 billion people",
   "What do you do": "I am a chatbot, my main function is to respond to your queries and converse with you."
}

def chat(message):
    
    if message in conversations.keys():
        return conversations[message]
    else:
      max = 0 
      maxsentence = ''
      
      for sentence in conversations.keys():
        if cal_cossimilarity(sentence,message) > max :
          max = cal_cossimilarity(sentence,message)
          maxsentence = sentence 
      
      if max > 0.1:
        return conversations[maxsentence]

      else:

        return "I'm sorry, I don't understand what you're saying."

print(chat("hello"))
print(chat("hi"))
print(chat("how are you"))
print(chat("bye!"))


Hello!
Hi!
I'm doing well, thank you.
Goodbye!


In [112]:
reviews = [
    "I hated this movie so much.",
    "The plot was incredibly boring.",
    "I couldn't finish watching this.",
    "The acting was terrible.",
    "I'm not sure why anyone liked this movie.",
    "This is my new favorite film.",
    "I couldn't take my eyes off the screen!",
    "I laughed so hard during this movie.",
    "I want to see this again and again.",
    "The ending was so satisfying.",

    "I felt like I wasted my time with this one.",

    "I was pleasantly surprised by this film.",
    "I couldn't stop thinking about this movie afterwards.",
    "This film was not what I was expecting.",

    "I was completely drawn in by the story.",
    "I couldn't stand the main character.",

    "I thought the special effects were impressive.",
    "This movie left me feeling so uplifted.",

    "I was disappointed by the lack of character development.",
    "The pacing of this movie was just perfect.",
    "I thought the soundtrack was incredibly well done.",
    "I hated the way the story was told.",
    "I was so excited to see this movie.",
    "I was let down by the acting.",
    "I thought the cinematography was breathtaking.",

    "This movie exceeded all of my expectations.",
    "I was so pleased with the way everything was tied together.",
    "I felt like I was watching a masterpiece."
]

labels = [
    0,  # negative
    0,  # negative
    0,  # negative
    0,  # negative
    0,  # negative
    1,  # positive
    1,  # positive
    1,  # positive
    1,  # positive
    1,  # positive

    0,  # negative

    1,  # positive
    1,  # positive
    0,  # negative

    1,  # positive
    0,  # negative

    1,  # positive
    1,  # positive

    0,  # negative
    1,  # positive
    1,  # positive
    0,  # negative
    1,  # positive
    0,  # negative
    1,  # positive

    1,  # positive
    1,  # positive
    1   # positive
]



reviews_test = ["A powerful and emotional film that tells a deeply moving story of hope, friendship, and redemption. The performances by actors are exceptional, and the direction is masterful.",
           "A thrilling and suspenseful adventure with amazing special effects",
            "A heartwarming tale that is both funny and emotional",
           "A cinematic masterpiece with iconic performances and a gripping story",
           "An unwatchable and poorly made film, with terrible acting and writing",
           "A pointless and uninspired animation, with no redeeming qualities",
            "A poorly executed and unfaithful adaptation of the original story",
           "A forgettable and uninspired film with a lackluster cast",
           "A mind-bending and well-crafted thriller with a shocking twist",
           "A thrilling adventure movie with great special effects"
]
labels_test = [1, 1, 1, 1, 0, 0, 0, 0, 1, 1]

In [108]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier as KNC
from sklearn.tree import DecisionTreeClassifier

# Splitting the dataset into training and testing sets
reviews_train = reviews
reviews_test = reviews_test
labels_train = labels
labels_test = labels_test

# bag-of-words representation
vectorizer = CountVectorizer()
reviews_train_features = vectorizer.fit_transform(reviews_train)
reviews_test_features = vectorizer.transform(reviews_test)

'''
# Training a Naive Bayes classifier
classifier = MultinomialNB()
classifier.fit(reviews_train_features, labels_train)
'''

'''
# Training a svm
classifier = SVC(kernel='linear', C=1.0, random_state=1) 
classifier.fit(reviews_train_features, labels_train)
'''

'''
# Training a logisticRegression
classifier = LogisticRegression(solver='liblinear', multi_class='auto',C=100.0, random_state=78)
classifier.fit(reviews_train_features, labels_train)
'''


# Training a KNN
classifier = KNC(n_neighbors=1, p=2, metric='minkowski')
classifier.fit(reviews_train_features, labels_train)


'''
# Training a decision tree
classifier = DecisionTreeClassifier()
classifier = classifier.fit(reviews_train_features, labels_train)
'''

# Evaluate
predictions = classifier.predict(reviews_test_features)
accuracy = accuracy_score(labels_test, predictions)
print("Accuracy:", accuracy)


Accuracy: 0.8


In [109]:
# Naive 분류기 구현 

reviews = [   
    ('fun,couple,love,love', 'comedy'),
    ('fast,furious,shoot', 'action'),
    ('couple,fly,fast,fun,fun', 'comedy'),
    ('furious,shoot,shoot,fun', 'action'),
    ('fly,fast,shoot,love', 'action')]


def get_words_category(reviews):
  action_words, comedy_words = [],[]
  for words in reviews:
    wordlist = words[0].split(',')
    if words[1] == 'action':
      action_words = action_words + wordlist
    if words[1] == 'comedy':
      comedy_words = comedy_words + wordlist  
  
  return action_words, comedy_words

def predict (review, priorA, priorC, wordsA, wordsC):

  number = len(set(wordsA+wordsC))
  wordlist = review.split(',')
  p_A,p_C = 1,1 
  for word in wordlist:
    p_A *= (wordsA.count(word)+1)/(len(wordsA)+number)
    p_C *= (wordsC.count(word)+1)/(len(wordsC)+number)
  if p_A >= p_C:
    predicted_class = 'action'
  else:
    predicted_class  = 'comedy'
    
  return predicted_class

     
def get_prior (reviews):
  prior_action, prior_comedy = 0,0
  for words in reviews:
    if words[1] == 'action':
      prior_action += 1 
    if words[1] == 'comedy':
      prior_comedy += 1
  sum = prior_comedy + prior_action 
  prior_action, prior_comedy = prior_action/sum, prior_comedy/sum
  return prior_action, prior_comedy


priorA, priorC = get_prior(reviews)
wordListA, wordListC = get_words_category(reviews)
review1 = 'fast,furious,shoot,love'
review2 = 'fast,fun,fun,love,fun'
print( review1 + ' belongs to '+ predict(review1, priorA, priorC, wordListA, wordListC))
print( review2 + ' belongs to '+ predict(review2, priorA, priorC, wordListA, wordListC))



fast,furious,shoot,love belongs to action
fast,fun,fun,love,fun belongs to comedy
